non_immigrant_visas = {
    "A1":	"Ambassador, Public Minister, Career Diplomat or Consular Officer, or Immediate Family",
    "A2":	"Other Foreign Government Official or Employee, or Immediate Family",
    "A3":	"Attendant, Servant, or Personal Employee of A1 or A2, or Immediate Family",
    "B1":	"Temporary Visitor for Business",
    "B2":	"Temporary Visitor for Pleasure",
    "B1/B2":"Temporary Visitor for Business & Pleasure",
    "C1":	"Alien in Transit",
    "C1/D": "Combined Transit and Crewmember Visa",
    "C2":	"Alien in Transit to United Nations Headquarters District Under Section 11.(3), (4), or (5) of the Headquarters Agreement",
    "C3":	"Foreign Government Official, Immediate Family, Attendant, Servant or Personal Employee, in Transit",
    "CW1":	"Commonwealth of Northern Mariana Islands Transitional Worker",
    "CW2":	"Spouse or Child of CW1",
    "D":	"Crewmember (Sea or Air)",
    "E1":	"Treaty Trader, Spouse or Child",
    "E2":	"Treaty Investor, Spouse or Child",
    "E2C":	"Commonwealth of Northern Mariana Islands Investor, Spouse or Child",
    "E3":	"Australian Treaty Alien coming to the United States Solely to Perform Services in a Specialty Occupation",
    "E3D":	"Spouse or Child of E3",
    "E3R":	"Returning E3",
    "F1":	"Student in an academic or language training program",
    "F2":	"Spouse or Child of F1",
    "F3":	"Canadian or Mexican national commuter student in an academic or language training program",
    "G1":	"Principal Resident Representative of Recognized Foreign Government to International Organization, Staff, or Immediate Family",
    "G2":	"Other Representative of Recognized Foreign Member Government to International Organization, or Immediate Family",
    "G3":	"Representative of Nonrecognized or Nonmember Foreign Government to International Organization, or Immediate Family",
    "G4":	"International Organization Officer or Employee, or Immediate Family",
    "G5":	"Attendant, Servant, or Personal Employee of G1 through G4, or Immediate Family",
    "H1B":	"Alien in a Specialty Occupation (Profession)",
    "H1B1":	"Chilean or Singaporean National to Work in a Specialty Occupation",
    "H1C":	"Nurse in health professional shortage area",
    "H2A":	"Temporary Worker Performing Agricultural Services Unavailable in the United States",
    "H2B":	"Temporary Worker Performing Other Services Unavailable in the United States",
    "H3":	"Trainee",
    "H4":	"Spouse or Child of Alien Classified H1B/B1/C, H2A/B, or H–3",
    "I":	"Representative of Foreign Information Media, Spouse and Child",
    "J1":	"Exchange Visitor",
    "J2":	"Spouse or Child of J1",
    "K1":	"Fiance(e) of United States Citizen",
    "K2":	"Child of Fiance(e) of U.S. Citizen",
    "K3":	"Spouse of U.S. Citizen awaiting availability of immigrant visa",
    "K4":	"Child of K3",
    "L1":	"Intracompany Transferee (Executive, Managerial, and Specialized Knowledge Personnel Continuing Employment with International Firm or Corporation)",
    "L2":	"Spouse or Child of Intracompany Transferee",
    "M1":	"Vocational Student or Other Nonacademic Student",
    "M2":	"Spouse or Child of M1",
    "M3":	"Canadian or Mexican national commuter student (Vocational student or other nonacademic student)",
    "N8":	"Parent of an Alien Classified SK3 or SN3",
    "N9":	"Child of N8 or of SK1, SK2, SK4, SN1, SN2 or SN4",
    "NATO 1":	"Principal Permanent Representative of Member State to NATO (including any of its Subsidiary Bodies) Resident in the U.S. and Resident Members of Official Staff; Secretary General, Assistant Secretaries General, and Executive Secretary of NATO; Other Permanent NATO Officials of Similar Rank, or Immediate Family",
    "NATO 2":	"Other Representative of member state to NATO (including any of its Subsidiary Bodies) including Representatives, Advisers, and Technical Experts of Delegations, or Immediate Family; Dependents of Member of a Force Entering in Accordance with the Provisions of the NATO Status-of-Forces Agreement or in Accordance with the provisions of the “Protocol on the Status of International Military Headquarters”; Members of Such a Force if Issued Visas",
    "NATO 3":	"Official Clerical Staff Accompanying Representative of Member State to NATO (including any of its Subsidiary Bodies), or Immediate Family",
    "NATO 4":	"Official of NATO (Other Than Those Classifiable as NATO1), or Immediate Family",
    "NATO 5":	"Experts, Other Than NATO Officials Classifiable Under NATO4, Employed in Missions on Behalf of NATO, and their Dependents",
    "NATO 6":	"Member of a Civilian Component Accompanying a Force Entering in Accordance with the Provisions of the NATO Status-of-Forces Agreement; Member of a Civilian Component Attached to or Employed by an Allied Headquarters Under the “Protocol on the Status of International Military Headquarters” Set Up Pursuant to the North Atlantic Treaty; and their Dependents",
    "NATO 7":	"Attendant, Servant, or Personal Employee of NATO1, NATO2, NATO 3, NATO4, NATO5, and NATO6 Classes, or Immediate Family",
    "O1":	"Alien with Extraordinary Ability in Sciences, Arts, Education, Business or Athletics",
    "O2":	"Alien Accompanying and Assisting in the Artistic or Athletic Performance by O1",
    "O3":	"Spouse or Child of O1 or O2",
    "P1":	"Internationally Recognized Athlete or Member of Internationally Recognized Entertainment Group",
    "P2":	"Artist or Entertainer in a Reciprocal Exchange Program",
    "P3":	"Artist or Entertainer in a Culturally Unique Program",
    "P4":	"Spouse or Child of P1, P2, or P3",
    "Q1":	"Participant in an International Cultural Exchange Program",
    "R1":	"Alien in a Religious Occupation",
    "R2":	"Spouse or Child of R1",
    "S5":	"Certain Aliens Supplying Critical Information Relating to a Criminal Organization or Enterprise",
    "S6":	"Certain Aliens Supplying Critical Information Relating to Terrorism",
    "S7":	"Qualified Family Member of S5 or S6",
    "T1":	"Victim of a severe form of trafficking in persons",
    "T2":	"Spouse of T1",
    "T3":	"Child of T1",
    "T4":	"Parent of T1",
    "T5":	"Unmarried Sibling under age 18 of T1",
    "T6":	"Adult or Minor Child of a Derivative Beneficiary of a T1",
    "TN":	"NAFTA Professional",
    "TD":	"Spouse or Child of NAFTA Professional",
    "U1":	"Victim of criminal activity",
    "U2":	"Spouse of U1",
    "U3":	"Child of U1",
    "U4":	"Parent of U1 under 21 years of age",
    "U5":	"Unmarried Sibling under age 18 of U1 under 21 years of age",
    "V1":	"Spouse of a Lawful Permanent Resident Alien Awaiting Availability of Immigrant Visa",
    "V2":	"Child of a Lawful Permanent Resident Alien Awaiting Availability of Immigrant Visa",
    "V3":	"Child of a V1 or V2"
}

immigrant_visas = {
    "IR1":	"Spouse of U.S. Citizen",
    "IR2":	"Child of U.S. Citizen",
    "IR3":	"Orphan Adopted Abroad by U.S. Citizen",
    "IH3":	"Child from Hague Convention Country Adopted Abroad by U.S. Citizen",
    "IR4":	"Orphan to be Adopted in U.S. by U.S. Citizen",
    "IH4":	"Child from Hague Convention Country to be Adopted in U.S. by U.S. Citizen",
    "IR5":	"Parent of U.S. Citizen at Least 21 Years of Age",
    "CR1":	"Spouse of U.S. Citizen (Conditional Status)",
    "CR2":	"Stepchild of U.S. Citizen (Conditional Status)",
    "IW1":	"Certain Spouses of Deceased U.S. Citizens",
    "IW2":	"Child of IW1",
    "IB1":	"Self-petition Spouse of U.S. Citizen",
    "IB2":	"Self-petition child of U.S. Citizen",
    "IB3":	"Child of IB1",
    "AM1":	"Vietnam Amerasian Principal",
    "AM2":	"Spouse or Child of AM1",
    "AM3":	"Natural Mother of AM1 (and Spouse or Child of Such Mother) or Person Who has Acted in Effect as the Mother, Father, or Next-of-Kin of AM1 (and Spouse or Child of Such Person)",
    "SB1":	"Returning Resident",
    "SC1":	"Person Who Lost U.S. Citizenship by Marriage",
    "SC2":	"Person Who Lost U.S. Citizenship by Serving in Foreign Armed Forces",
    "SI1":	"Certain Aliens Employed by the U.S. Government in Iraq or Afghanistan as Translators or Interpreters",
    "SI2":	"Spouse of SI1",
    "SI3":	"Child of SI1",
    "SM1":	"Alien Recruited Outside the United States Who Has Served or is Enlisted to Serve in the U.S. Armed Forces for 12 Years",
    "SM2":	"Spouse of SM1",
    "SM3":	"Child of SM1",
    "SQ1":	"Certain Iraqis or Afghans Employed by or on Behalf of the U.S. Government",
    "SQ2":	"Spouse of SQ1",
    "SQ3":	"Child of SQ1",
    "SU2":	"Spouse of U1",
    "SU3":	"Child of U1",
    "SU5":	"Parent of U1",
    "F11":	"Unmarried Son or Daughter of U.S. Citizen",
    "F12":	"Child of F11",
    "B11":	"Self-petition Unmarried Son or Daughter of U.S. Citizen",
    "B12":	"Child of B11",
    "F21":	"Spouse of Lawful Permanent Resident",
    "F22":	"Child of Lawful Permanent Resident",
    "F23":	"Child of F21 or F22",
    "F24":	"Unmarried Son or Daughter of Lawful Permanent Resident",
    "F25":	"Child of F24",
    "C21":	"Spouse of Lawful Permanent Resident (Conditional)",
    "C22":	"Stepchild of Alien Resident (Conditional)",
    "C23":	"Child of C21 or C22 (Conditional)",
    "C24":	"Unmarried Son or Daughter of Lawful Permanent Resident (Conditional)",
    "C25":	"Child of F24 (Conditional)",
    "B21":	"Self-petition Spouse of Lawful Permanent Resident",
    "B22":	"Self-petition Child of Lawful Permanent Resident",
    "B23":	"Child of B21 or B22",
    "B24":	"Self-petition Unmarried Son or Daughter of Lawful Permanent Resident",
    "B25":	"Child of B24",
    "FX1":	"Spouse of Lawful Permanent Resident",
    "FX2":	"Child of Lawful Permanent Resident",
    "FX3":	"Child of FX1 or FX2",
    "CX1":	"Spouse of Lawful Permanent Resident (Conditional)",
    "CX2":	"Stepchild of Lawful Permanent Resident (Conditional)",
    "CX3":	"Child of CX1 or CX2 (Conditional)",
    "BX1":	"Self-petition Spouse of Lawful Permanent Resident",
    "BX2":	"Self-petition Child of Lawful Permanent Resident",
    "BX3":	"Child of BX1 or BX2",
    "F31":	"Married Son or Daughter of U.S. Citizen",
    "F32":	"Spouse of F31",
    "F33":	"Child of F31",
    "C31":	"Married Son or Daughter of U.S. Citizen (Conditional)",
    "C32":	"Spouse of C31 (Conditional)",
    "C33":	"Child of C31 (Conditional)",
    "B31":	"Self-petition Married Son or Daughter of U.S. Citizen",
    "B32":	"Spouse of B31",
    "B33":	"Child of B31",
    "F41":	"Brother or Sister of U.S. Citizen at Least 21 Years of Age",
    "F42":	"Spouse of F41",
    "F43":	"Child of F41",
    "E11":	"Alien with Extraordinary Ability",
    "E12":	"Outstanding Professor or Researcher",
    "E13":	"Multinational Executive or Manager",
    "E14":	"Spouse of E11, E12, or E13",
    "E15":	"Child of E11, E12, or E13",
    "E21":	"Professional Holding Advanced Degree or Alien of Exceptional Ability",
    "E22":	"Spouse of E21",
    "E23":	"Child of E21",
    "E31":	"Skilled Worker",
    "E32":	"Professional Holding Baccalaureate Degree",
    "E34":	"Spouse of E31 or E32",
    "E35":	"Child of E31 or E32",
    "EW3":	"Other Worker (Subgroup Numerical Limit)",
    "EW4":	"Spouse of EW3",
    "EW5":	"Child of EW3",
    "BC1":	"Broadcaster in the U.S. employed by the International Broadcasting Bureau of the Broadcasting Board of Governors or a grantee of such organization",
    "BC2":	"Accompanying spouse of BC1",
    "BC3":	"Accompanying child of BC1",
    "SD1":	"Minister of Religion",
    "SD2":	"Spouse of SD1",
    "SD3":	"Child of SD1",
    "SE1":	"Certain Employees or Former Employees of the U.S. Government Abroad",
    "SE2":	"Spouse of SE1",
    "SE3":	"Child of SE1",
    "SF1":	"Certain Former Employees of the Panama Canal Company or Canal Zone Government",
    "SF2":	"Spouse or Child of SF1",
    "SG1":	"Certain Former Employees of the U.S. Government in the Panama Canal Zone",
    "SG2":	"Spouse or Child of SG1",
    "SH1":	"Certain Former Employees of the Panama Canal Company or Canal Zone Government on April 1, 1979",
    "SH2":	"Spouse or Child of SH1",
    "SJ1":	"Certain Foreign Medical Graduates (Adjustments Only)",
    "SJ2":	"Accompanying Spouse or Child of SJ1",
    "SK1":	"Certain Retired International Organization employees",
    "SK2":	"Spouse of SK1",
    "SK3":	"Certain Unmarried Sons or Daughters of an International Organization Employee",
    "SK4":	"Certain Surviving Spouses of a deceased International Organization Employee",
    "SL1":	"Juvenile Court Dependent (Adjustment Only)",
    "SN1":	"Certain retired NATO6 civilians",
    "SN2":	"Spouse of SN1",
    "SN3":	"Certain unmarried sons or daughters of NATO6 civilian employees",
    "SN4":	"Certain surviving spouses of deceased NATO6 civilian employees",
    "SP":	"Alien Beneficiary of a petition or labor certification application filed prior to September 11, 2001, if the petition or application was rendered void due to a terrorist act of September 11, 2001. Spouse, child of such alien, or the grandparent of a child orphaned by a terrorist act of September 11, 2001",
    "SR1":	"Certain Religious Workers",
    "SR2":	"Spouse of SR1",
    "SR3":	"Child of SR1",
    "C51":	"Employment Creation OUTSIDE Targeted Areas",
    "C52":	"Spouse of C51",
    "C53":	"Child of C51",
    "T51":	"Employment Creation IN Targeted Rural/High Unemployment Area",
    "T52":	"Spouse of T51",
    "T53":	"Child of T51",
    "R51":	"Investor Pilot Program, Not in Targeted Area",
    "R52":	"Spouse of R51",
    "R53":	"Child of R51",
    "I51":	"Investor Pilot Program, in Targeted Area",
    "I52":	"Spouse of I51",
    "I53":	"Child of I51",
    "DV1":	"Diversity Immigrant",
    "DV2":	"Spouse of DV1",
    "DV3":	"Child of DV1"
}
